FROM jenkins/jenkins
 

ENV JAVA_OPTS -Djenkins.install.runSetupWizard=false
# ENV CASC_JENKINS_CONFIG /var/jenkins_home/plugins.txt
# COPY casc.yaml /var/jenkins_home/casc.yaml
# COPY plugins.txt /var/jenkins_home/plugins.txt
# RUN jenkins-plugin-cli --plugins sshd:3.312.v1c601b_c83b_0e
# RUN jenkins-plugin-cli --plugins workflow-job:1360.vc6700e3136f5
# RUN jenkins-plugin-cli --verbose --plugin-file /var/jenkins_home/plugins.txt
# RUN /usr/local/bin/install-plugins.sh < /usr/share/jenkins/ref/plugins.txt
