jenkins:
  securityRealm:
    local:
      allowsSignup: false
      users:
       - id: Admin
         password: Admin123456
authorizationStrategy:
    globalMatrix:
      permissions:
        - "USER:Overall/Administer:admin"
        - "GROUP:Overall/Read:authenticated"
    remotingSecurity:
      enabled: true

security:
  queueItemAuthenticator:
    authenticators:
    - global:
        strategy: triggeringUsersAuthorizationStrategy

unclassified:
  location:
    url: http://localhost:8080/