---
- name: Install docker repository
  hosts: Jenkins
  become: true

  tasks:
    - name: Install required system packages
      apt:
        pkg:
          - ca-certificates
          - curl
          - python3-pip
          - zip
          - gnupg
          - lsb-release
        state: latest
        update_cache: true

    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu focal stable
        state: present

    - name: Install docker
      apt:
        pkg:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: latest
        update_cache: true

    - name: Install Docker Module for Python
      pip:
        name:
          - docker
        state: latest

    - name: Add "{{ ansible_user }}" to docker group
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: true 